name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: yarn install --frozen-lockfile
      - run: yarn run build
      - run: rm -rf node_modules
      - uses: ./
      - uses: ./
        with:
          person: 'Batman'